config/routes.rb
Rails.application.routes.draw do
  resources :app_usages

  resources :app_sessions

  resources :system_settings

  resources :user_activities

  resources :user_locations

  resources :devices

  get 'welcome/index'

  root 'welcome#index'

end

app/models/app_session.rb
class AppSession < ActiveRecord::Base
  belongs_to :device
  has_many :app_usages
end

app/controllers/app_sessions_controller.rb
class AppSessionsController < ApplicationController
  before_action :set_app_session, only: [:show, :edit, :update, :destroy]

  # GET /app_sessions
  # GET /app_sessions.json
  def index
    @app_sessions = AppSession.all
  end

  # GET /app_sessions/1
  # GET /app_sessions/1.json
  def show
  end

  # GET /app_sessions/new
  def new
    @app_session = AppSession.new
  end

  # GET /app_sessions/1/edit
  def edit
  end

  # POST /app_sessions
  # POST /app_sessions.json
  def create
    @app_session = AppSession.new(app_session_params)

    respond_to do |format|
      if @app_session.save
        format.html { redirect_to @app_session, notice: 'App session was successfully created.' }
        format.json { render :show, status: :created, location: @app_session }
      else
        format.html { render :new }
        format.json { render json: @app_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_sessions/1
  # PATCH/PUT /app_sessions/1.json
  def update
    respond_to do |format|
      if @app_session.update(app_session_params)
        format.html { redirect_to @app_session, notice: 'App session was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_session }
      else
        format.html { render :edit }
        format.json { render json: @app_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_sessions/1
  # DELETE /app_sessions/1.json
  def destroy
    @app_session.destroy
    respond_to do |format|
      format.html { redirect_to app_sessions_url, notice: 'App session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_session
      @app_session = AppSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_session_params
      params.require(:app_session).permit(:app_session_timestamp_start, :app_session_timestamp_end, :app_session_timestamp_duration, :device_id)
    end
end

app/helpers/app_sessions_helper.rb
module AppSessionsHelper
end

app/views/app_sessions/_form.html.erb
<%= form_for(@app_session) do |f| %>
  <% if @app_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_session.errors.count, "error") %> prohibited this app_session from being saved:</h2>

      <ul>
      <% @app_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_session_timestamp_start %><br>
    <%= f.datetime_select :app_session_timestamp_start %>
  </div>
  <div class="field">
    <%= f.label :app_session_timestamp_end %><br>
    <%= f.datetime_select :app_session_timestamp_end %>
  </div>
  <div class="field">
    <%= f.label :app_session_timestamp_duration %><br>
    <%= f.datetime_select :app_session_timestamp_duration %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.number_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_sessions/edit.html.erb
<h1>Editing app_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_session %> |
<%= link_to 'Back', app_sessions_path %>

app/views/app_sessions/index.html.erb
<h1>Listing app_sessions</h1>

<table>
  <thead>
    <tr>
      <th>App session timestamp start</th>
      <th>App session timestamp end</th>
      <th>App session timestamp duration</th>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_sessions.each do |app_session| %>
      <tr>
        <td><%= app_session.app_session_timestamp_start %></td>
        <td><%= app_session.app_session_timestamp_end %></td>
        <td><%= app_session.app_session_timestamp_duration %></td>
        <td><%= app_session.device_id %></td>
        <td><%= link_to 'Show', app_session %></td>
        <td><%= link_to 'Edit', edit_app_session_path(app_session) %></td>
        <td><%= link_to 'Destroy', app_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App session', new_app_session_path %>

app/views/app_sessions/new.html.erb
<h1>New app_session</h1>

<%= render 'form' %>

<%= link_to 'Back', app_sessions_path %>

app/views/app_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App session timestamp start:</strong>
  <%= @app_session.app_session_timestamp_start %>
</p>

<p>
  <strong>App session timestamp end:</strong>
  <%= @app_session.app_session_timestamp_end %>
</p>

<p>
  <strong>App session timestamp duration:</strong>
  <%= @app_session.app_session_timestamp_duration %>
</p>

<p>
  <strong>Device:</strong>
  <%= @app_session.device_id %>
</p>

<%= link_to 'Edit', edit_app_session_path(@app_session) %> |
<%= link_to 'Back', app_sessions_path %>