config/routes.rb
Rails.application.routes.draw do
  resources :app_usages

  resources :app_sessions

  resources :system_settings

  resources :user_activities

  resources :user_locations

  resources :devices

  get 'welcome/index'

  root 'welcome#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :user_locations
  has_many :user_activities
  has_many :app_sessions
  has_many :system_settings
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    # before filling the db with json data, remove all entries and reset autoincrement ids
    Device.delete_all
    ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'devices'")
    UserLocation.delete_all
    ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'user_locations'")
    UserActivity.delete_all
    ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'user_activities'")
    AppSession.delete_all
    ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'app_sessions'")
    AppUsage.delete_all
    ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'app_usages'")
    SystemSetting.delete_all
    ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'system_settings'")

    # Read file contents
    # http://stackoverflow.com/questions/2521053/how-to-read-a-user-uploaded-file-without-saving-it-to-the-database
    file_data = device_params[:json_file]
    if file_data.respond_to?(:read)
      json_contents = file_data.read
    elsif file_data.respond_to?(:path)
      json_contents = File.read(file_data.path)
    else
      logger.error "Bad file_data: #{file_data.class.name}: #{file_data.inspect}"
      json_contents = nil
    end

    if json_contents != nil
      @devices = JSON.parse(json_contents)

      @devices['mongoexport'].each do |device|
        generated_params = {}

        # device infos
        generated_params[:mongo_id] = device['_id']['$oid']
        generated_params[:uuid] = device['uuid']
        generated_params[:android_id] = device['system_infos']['android_id']
        generated_params[:user_name] = device['system_infos']['user_name']
        generated_params[:os_version] = device['system_infos']['os_version']
        generated_params[:model] = device['system_infos']['model']
        generated_params[:product] = device['system_infos']['product']
        generated_params[:manufacturer] = device['system_infos']['manufacturer']
        generated_params[:brand] = device['system_infos']['brand']
        generated_params[:created_at] = Time.at(device['created_at']['$date']/1000.0)
        generated_params[:updated_at] = Time.at(device['updated_at']['$date']/1000.0)

        @device = Device.new(generated_params)
        device_created = @device.save
        puts "Device ID: #{@device.id}"

        # if device_created && device['system_infos']['user_name'] == 'Thomas Kowar' then
        if device_created then
          # remove duplicates from app sessions
          if device['app_sessions'] != nil then
            app_sessions_no_duplicates = device['app_sessions'].uniq { |app_session| [ app_session['app_session_timestamp_start'], app_session['app_session_timestamp_end'], app_session['app_session_timestamp_duration'], app_session['server_sent'] ] }
            puts "Removed #{device['app_sessions'].length-app_sessions_no_duplicates.length} duplicate entries. From #{device['app_sessions'].length} to #{app_sessions_no_duplicates.length}"
          
            app_sessions = []
            app_sessions_no_duplicates.each_with_index do |app_session, index|
              # puts index
              app_sessions << index+1
            end
            puts "App Session IDs (App Sessions): #{app_sessions}"
          end

          if device['app_usages'] != nil then
            app_usages = []
            device['app_usages'].each do |app_usage|
              app_usages << app_usage['app_session_id']
              # puts "ID: #{app_usage['app_sessions_id']}"
              # app_usages << app_usage['app_sessions_id']
            end
            puts "App Session IDs (App Usages): #{app_usages.uniq}"
          end

          # related data: user locations
          if device['user_locations'] != nil then
            user_locations = []
            device['user_locations'].each do |user_location|
              user_location[:device_id] = @device.id
              user_locations << UserLocation.new(user_location.except('_id', 'server_sent'))
            end

            UserLocation.import user_locations
          end


          # related data: user activities
          if device['user_activities'] != nil then
            user_activities = []
            device['user_activities'].each do |user_activity|
              user_activity[:device_id] = @device.id
              user_activities << UserActivity.new(user_activity.except('_id', 'server_sent'))
            end

            # @device.user_activities.push(user_activities)
            UserActivity.import user_activities
          end

          # related data: app usages => WARNING: Have to be inserted before app_sessions (because of inserting IDs correctly)
          # if device['app_usages'] != nil then
          #   app_usages = []
          #   device['app_usages'].each do |app_usage|
          #     # puts "#{app_usage['app_session_id']}"
          #     puts "Last App Session Entry ID #{AppSession.last.id}"
          #     # app_usage['app_session_id'] = app_usage['app_session_id']
          #     app_usages << AppUsage.new(app_usage.except('_id', 'server_sent'))
          #   end
          #   AppUsage.import app_usages
          # end

          # related data: app sessions
          if app_sessions_no_duplicates != nil then
            app_sessions_no_duplicates.each_with_index do |app_session, index|
              app_session[:device_id] = @device.id
              app_session_id = index + 1

              # temp variable to get id
              app_session_temp = AppSession.new(app_session.except('_id', 'server_sent'))
              app_session_temp.save!

              puts "App Session Temp ID: #{app_session_temp.id}"
              puts "App Session ID: #{app_session_id}"

              # related data: app usages
              if device['app_usages'] != nil then
                # app_usages = []
                # device['app_usages'].each do |app_usage|
                #   app_usages << app_usage['app_session_id']
                # end
                # app_usages.uniq!

                app_usages_for_saved_app_session = device['app_usages'].select { |app_usage| app_usage['app_session_id'] == app_session_id }
                
                puts "App Usages: #{app_usages_for_saved_app_session}"
                if app_usages_for_saved_app_session != [] then
                  app_usages = []
                  app_usages_for_saved_app_session.each do |app_usage|
                    app_usage[:app_session_id] = app_session_temp.id
                    puts "App Usage saved with Session ID = #{app_session_temp.id}"
                    app_usages << AppUsage.new(app_usage.except('_id', 'server_sent'))
                  end
                  AppUsage.import app_usages
                end

                # puts "App Usage Session IDs: #{app_usages}"
              end
            end
          end

          # if device['app_sessions'] != nil then
          #   app_sessions = []
            
          #   device['app_sessions'].each do |app_session|

          #     app_session[:device_id] = @device.id
          #     app_session_temp = AppSession.new(app_session.except('_id', 'server_sent'))

          #     if device['app_usages'] != nil then
          #       # ActiveRecord::Base.transaction do
          #         app_usages = []
          #         device['app_usages'].each do |app_usage|
          #           app_usages << AppUsage.new(app_usage.except('_id', 'server_sent'))
          #           # app_usages.push HTMLEntities.new.encode "(#{app_usage['app_name']},
          #           #                   #{app_usage['package_name']},
          #           #                   #{app_usage['version_name']},
          #           #                   #{app_usage['version_code']},
          #           #                   #{app_usage['base_activity']},
          #           #                   #{app_usage['top_activity']},
          #           #                   #{app_usage['first_install_time']},
          #           #                   #{app_usage['last_update_time']},
          #           #                   #{app_usage['app_session_id']},
          #           #                   #{app_usage['created_at']},
          #           #                   #{app_usage['updated_at']}
          #           #                   )".to_s
          #         end

          #         AppUsage.import app_usages
          #         # app_session_temp.app_usages.push(app_usages)
          #         # sql = "INSERT INTO app_usages (`app_name`, `package_name`, `version_name`, `version_code`, `base_activity`, `top_activity`, `first_install_time`, `last_update_time`, `app_session_id`, `created_at`, `updated_at`) VALUES #{app_usages.join(", ")}"
          #         # ActiveRecord::Base.connection.execute(sql)
          #       # end
          #     end

          #     app_sessions << app_session_temp
          #   end

          #   # @device.app_sessions.push(app_sessions)
          #   AppSession.import app_sessions
          # end
        
          # related data: system settings
          if device['system_settings'] != nil then
            system_settings = []
            device['system_settings'].each do |system_setting|
              system_settings << SystemSetting.new(system_setting.except('_id', 'server_sent'))
            end
            # @device.system_settings.push(system_settings)
            SystemSetting.import system_settings
          end
        end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f|  %>
  <%= f.file_field  :json_file %>
  <%= f.submit "Datei hochladen", class: "button" %>
<%end%>

<!-- <%#= form_for(@device) do |f| %>
  <%# if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <%# @device.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="field">
    <%#= f.label :user_name %><br>
    <%#= f.text_field :user_name %>
  </div>
  <div class="field">
    <%#= f.label :mongo_id %><br>
    <%#= f.text_field :mongo_id %>
  </div>
  <div class="field">
    <%#= f.label :uuid %><br>
    <%#= f.text_field :uuid %>
  </div>
  <div class="field">
    <%#= f.label :android_id %><br>
    <%#= f.text_field :android_id %>
  </div>
  <div class="field">
    <%#= f.label :created_at %><br>
    <%#= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%#= f.label :os_version %><br>
    <%#= f.text_field :os_version %>
  </div>
  <div class="field">
    <%#= f.label :model %><br>
    <%#= f.text_field :model %>
  </div>
  <div class="field">
    <%#= f.label :product %><br>
    <%#= f.text_field :product %>
  </div>
  <div class="field">
    <%#= f.label :manufacturer %><br>
    <%#= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%#= f.label :brand %><br>
    <%#= f.text_field :brand %>
  </div>
  <div class="field">
    <%#= f.label :user_locations %><br>
    <%#= f.number_field :user_locations %>
  </div>
  <div class="field">
    <%#= f.label :user_activities %><br>
    <%#= f.number_field :user_activities %>
  </div>
  <div class="field">
    <%#= f.label :app_sessions %><br>
    <%#= f.number_field :app_sessions %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div>
<%# end %>
 -->

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Mongo</th>
      <th>Uuid</th>
      <th>Android</th>
      <th>Created at</th>
      <th>Os version</th>
      <th>Model</th>
      <th>Product</th>
      <th>Manufacturer</th>
      <th>Brand</th>
      <th>User locations</th>
      <th>User activities</th>
      <th>App sessions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.user_name %></td>
        <td><%= device.mongo_id %></td>
        <td><%= device.uuid %></td>
        <td><%= device.android_id %></td>
        <td><%= device.created_at %></td>
        <td><%= device.os_version %></td>
        <td><%= device.model %></td>
        <td><%= device.product %></td>
        <td><%= device.manufacturer %></td>
        <td><%= device.brand %></td>
        <td><%= device.user_locations %></td>
        <td><%= device.user_activities %></td>
        <td><%= device.app_sessions %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @device.user_name %>
</p>

<p>
  <strong>Mongo:</strong>
  <%= @device.mongo_id %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @device.uuid %>
</p>

<p>
  <strong>Android:</strong>
  <%= @device.android_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @device.created_at %>
</p>

<p>
  <strong>Os version:</strong>
  <%= @device.os_version %>
</p>

<p>
  <strong>Model:</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Product:</strong>
  <%= @device.product %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @device.manufacturer %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @device.brand %>
</p>

<p>
  <strong>User locations:</strong>
  <%= @device.user_locations %>
</p>

<p>
  <strong>User activities:</strong>
  <%= @device.user_activities %>
</p>

<p>
  <strong>App sessions:</strong>
  <%= @device.app_sessions %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>