config/routes.rb
Rails.application.routes.draw do
  resources :app_usages

  resources :app_sessions

  resources :system_settings

  resources :user_activities

  resources :user_locations

  resources :devices

  get 'welcome/index'

  root 'welcome#index'

end

app/models/app_usage.rb
class AppUsage < ActiveRecord::Base
  belongs_to :app_session
end

app/controllers/app_usages_controller.rb
class AppUsagesController < ApplicationController
  before_action :set_app_usage, only: [:show, :edit, :update, :destroy]

  # GET /app_usages
  # GET /app_usages.json
  def index
    @app_usages = AppUsage.all
  end

  # GET /app_usages/1
  # GET /app_usages/1.json
  def show
  end

  # GET /app_usages/new
  def new
    @app_usage = AppUsage.new
  end

  # GET /app_usages/1/edit
  def edit
  end

  # POST /app_usages
  # POST /app_usages.json
  def create
    @app_usage = AppUsage.new(app_usage_params)

    respond_to do |format|
      if @app_usage.save
        format.html { redirect_to @app_usage, notice: 'App usage was successfully created.' }
        format.json { render :show, status: :created, location: @app_usage }
      else
        format.html { render :new }
        format.json { render json: @app_usage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_usages/1
  # PATCH/PUT /app_usages/1.json
  def update
    respond_to do |format|
      if @app_usage.update(app_usage_params)
        format.html { redirect_to @app_usage, notice: 'App usage was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_usage }
      else
        format.html { render :edit }
        format.json { render json: @app_usage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_usages/1
  # DELETE /app_usages/1.json
  def destroy
    @app_usage.destroy
    respond_to do |format|
      format.html { redirect_to app_usages_url, notice: 'App usage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_usage
      @app_usage = AppUsage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_usage_params
      params.require(:app_usage).permit(:app_name, :package_name, :version_name, :version_code, :base_activity, :top_activity, :first_install_time, :last_update_time, :app_session_id)
    end
end

app/helpers/app_usages_helper.rb
module AppUsagesHelper
end

app/views/app_usages/_form.html.erb
<%= form_for(@app_usage) do |f| %>
  <% if @app_usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_usage.errors.count, "error") %> prohibited this app_usage from being saved:</h2>

      <ul>
      <% @app_usage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_name %><br>
    <%= f.text_field :app_name %>
  </div>
  <div class="field">
    <%= f.label :package_name %><br>
    <%= f.text_field :package_name %>
  </div>
  <div class="field">
    <%= f.label :version_name %><br>
    <%= f.text_field :version_name %>
  </div>
  <div class="field">
    <%= f.label :version_code %><br>
    <%= f.number_field :version_code %>
  </div>
  <div class="field">
    <%= f.label :base_activity %><br>
    <%= f.text_field :base_activity %>
  </div>
  <div class="field">
    <%= f.label :top_activity %><br>
    <%= f.text_field :top_activity %>
  </div>
  <div class="field">
    <%= f.label :first_install_time %><br>
    <%= f.datetime_select :first_install_time %>
  </div>
  <div class="field">
    <%= f.label :last_update_time %><br>
    <%= f.datetime_select :last_update_time %>
  </div>
  <div class="field">
    <%= f.label :app_session_id %><br>
    <%= f.number_field :app_session_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_usages/edit.html.erb
<h1>Editing app_usage</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_usage %> |
<%= link_to 'Back', app_usages_path %>

app/views/app_usages/index.html.erb
<h1>Listing app_usages</h1>

<table>
  <thead>
    <tr>
      <th>App name</th>
      <th>Package name</th>
      <th>Version name</th>
      <th>Version code</th>
      <th>Base activity</th>
      <th>Top activity</th>
      <th>First install time</th>
      <th>Last update time</th>
      <th>App session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_usages.each do |app_usage| %>
      <tr>
        <td><%= app_usage.app_name %></td>
        <td><%= app_usage.package_name %></td>
        <td><%= app_usage.version_name %></td>
        <td><%= app_usage.version_code %></td>
        <td><%= app_usage.base_activity %></td>
        <td><%= app_usage.top_activity %></td>
        <td><%= app_usage.first_install_time %></td>
        <td><%= app_usage.last_update_time %></td>
        <td><%= app_usage.app_session_id %></td>
        <td><%= link_to 'Show', app_usage %></td>
        <td><%= link_to 'Edit', edit_app_usage_path(app_usage) %></td>
        <td><%= link_to 'Destroy', app_usage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App usage', new_app_usage_path %>

app/views/app_usages/new.html.erb
<h1>New app_usage</h1>

<%= render 'form' %>

<%= link_to 'Back', app_usages_path %>

app/views/app_usages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App name:</strong>
  <%= @app_usage.app_name %>
</p>

<p>
  <strong>Package name:</strong>
  <%= @app_usage.package_name %>
</p>

<p>
  <strong>Version name:</strong>
  <%= @app_usage.version_name %>
</p>

<p>
  <strong>Version code:</strong>
  <%= @app_usage.version_code %>
</p>

<p>
  <strong>Base activity:</strong>
  <%= @app_usage.base_activity %>
</p>

<p>
  <strong>Top activity:</strong>
  <%= @app_usage.top_activity %>
</p>

<p>
  <strong>First install time:</strong>
  <%= @app_usage.first_install_time %>
</p>

<p>
  <strong>Last update time:</strong>
  <%= @app_usage.last_update_time %>
</p>

<p>
  <strong>App session:</strong>
  <%= @app_usage.app_session_id %>
</p>

<%= link_to 'Edit', edit_app_usage_path(@app_usage) %> |
<%= link_to 'Back', app_usages_path %>