config/routes.rb
Rails.application.routes.draw do
  resources :app_usages

  resources :app_sessions

  resources :system_settings

  resources :user_activities

  resources :user_locations

  resources :devices

  get 'welcome/index'

  root 'welcome#index'

end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :device
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
  before_action :set_user_location, only: [:show, :edit, :update, :destroy]

  # GET /user_locations
  # GET /user_locations.json
  def index
    @user_locations = UserLocation.all
  end

  # GET /user_locations/1
  # GET /user_locations/1.json
  def show
  end

  # GET /user_locations/new
  def new
    @user_location = UserLocation.new
  end

  # GET /user_locations/1/edit
  def edit
  end

  # POST /user_locations
  # POST /user_locations.json
  def create
    @user_location = UserLocation.new(user_location_params)

    respond_to do |format|
      if @user_location.save
        format.html { redirect_to @user_location, notice: 'User location was successfully created.' }
        format.json { render :show, status: :created, location: @user_location }
      else
        format.html { render :new }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_locations/1
  # PATCH/PUT /user_locations/1.json
  def update
    respond_to do |format|
      if @user_location.update(user_location_params)
        format.html { redirect_to @user_location, notice: 'User location was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_location }
      else
        format.html { render :edit }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_locations/1
  # DELETE /user_locations/1.json
  def destroy
    @user_location.destroy
    respond_to do |format|
      format.html { redirect_to user_locations_url, notice: 'User location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_location
      @user_location = UserLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_location_params
      params.require(:user_location).permit(:location_timestamp, :location_elapsed_realtime_nanos, :location_provider, :location_latitude, :location_longitude, :location_altitude, :location_speed, :location_accuracy, :location_app_session_id)
    end
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/views/user_locations/_form.html.erb
<%= form_for(@user_location) do |f| %>
  <% if @user_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_location.errors.count, "error") %> prohibited this user_location from being saved:</h2>

      <ul>
      <% @user_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_timestamp %><br>
    <%= f.datetime_select :location_timestamp %>
  </div>
  <div class="field">
    <%= f.label :location_elapsed_realtime_nanos %><br>
    <%= f.number_field :location_elapsed_realtime_nanos %>
  </div>
  <div class="field">
    <%= f.label :location_provider %><br>
    <%= f.text_field :location_provider %>
  </div>
  <div class="field">
    <%= f.label :location_latitude %><br>
    <%= f.text_field :location_latitude %>
  </div>
  <div class="field">
    <%= f.label :location_longitude %><br>
    <%= f.text_field :location_longitude %>
  </div>
  <div class="field">
    <%= f.label :location_altitude %><br>
    <%= f.text_field :location_altitude %>
  </div>
  <div class="field">
    <%= f.label :location_speed %><br>
    <%= f.text_field :location_speed %>
  </div>
  <div class="field">
    <%= f.label :location_accuracy %><br>
    <%= f.text_field :location_accuracy %>
  </div>
  <div class="field">
    <%= f.label :location_app_session_id %><br>
    <%= f.number_field :location_app_session_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_locations/edit.html.erb
<h1>Editing user_location</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_location %> |
<%= link_to 'Back', user_locations_path %>

app/views/user_locations/index.html.erb
<h1>Listing user_locations</h1>

<table>
  <thead>
    <tr>
      <th>Location timestamp</th>
      <th>Location elapsed realtime nanos</th>
      <th>Location provider</th>
      <th>Location latitude</th>
      <th>Location longitude</th>
      <th>Location altitude</th>
      <th>Location speed</th>
      <th>Location accuracy</th>
      <th>Location app session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_locations.each do |user_location| %>
      <tr>
        <td><%= user_location.location_timestamp %></td>
        <td><%= user_location.location_elapsed_realtime_nanos %></td>
        <td><%= user_location.location_provider %></td>
        <td><%= user_location.location_latitude %></td>
        <td><%= user_location.location_longitude %></td>
        <td><%= user_location.location_altitude %></td>
        <td><%= user_location.location_speed %></td>
        <td><%= user_location.location_accuracy %></td>
        <td><%= user_location.location_app_session_id %></td>
        <td><%= link_to 'Show', user_location %></td>
        <td><%= link_to 'Edit', edit_user_location_path(user_location) %></td>
        <td><%= link_to 'Destroy', user_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User location', new_user_location_path %>

app/views/user_locations/new.html.erb
<h1>New user_location</h1>

<%= render 'form' %>

<%= link_to 'Back', user_locations_path %>

app/views/user_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location timestamp:</strong>
  <%= @user_location.location_timestamp %>
</p>

<p>
  <strong>Location elapsed realtime nanos:</strong>
  <%= @user_location.location_elapsed_realtime_nanos %>
</p>

<p>
  <strong>Location provider:</strong>
  <%= @user_location.location_provider %>
</p>

<p>
  <strong>Location latitude:</strong>
  <%= @user_location.location_latitude %>
</p>

<p>
  <strong>Location longitude:</strong>
  <%= @user_location.location_longitude %>
</p>

<p>
  <strong>Location altitude:</strong>
  <%= @user_location.location_altitude %>
</p>

<p>
  <strong>Location speed:</strong>
  <%= @user_location.location_speed %>
</p>

<p>
  <strong>Location accuracy:</strong>
  <%= @user_location.location_accuracy %>
</p>

<p>
  <strong>Location app session:</strong>
  <%= @user_location.location_app_session_id %>
</p>

<%= link_to 'Edit', edit_user_location_path(@user_location) %> |
<%= link_to 'Back', user_locations_path %>